universe = vanilla
Executable = /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/makeStep2.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Transfer_Input_Files = /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/makeStep2.C, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/step2.cc, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/step2.h, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/step2_cc.d, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/step2_cc.so, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/Davismt2.cc, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/Davismt2.h, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/Davismt2_cc.d, /user_data/jlee/TTTT/test/CMSSW_9_4_6_patch1/src/TTTT/step2/Davismt2_cc.so
Output = ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8_1_hadd.out
Error = ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8_1_hadd.err
Log = ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8_1_hadd.log
Notification = Never
Arguments = ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8_1_hadd.root ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8_1_hadd.root /mnt/hadoop/store/user/jblee/TTTT/LJMet94X_1lep_013019_step1_hadds/nominal/ /mnt/hadoop/store/user/jblee/TTTT/LJMet94X_1lepTT_013019_step2/nominal/

Queue 1